# Generated by Django 3.2 on 2021-04-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
                ('contact_website', models.URLField()),
                ('is_whatsapp_available', models.BooleanField()),
            ],
        ),
    ]
