# Generated by Django 3.2 on 2021-04-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid_resource', '0002_remove_covidresource_is_whatsapp_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidresource',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
